AGA8 WebAssembly: src/cpp/Gross.cpp File Reference
Gross.cpp File Reference
Implementation of AGA 8 Part 1 GROSS equation of state (Version 2.0)
#include "Gross.h"
#include <math.h>
#include <cmath>
#include <iostream>
#include <cstdlib>
Functions
void Bmix (const double T, const std::vector< double > &xGrs, const double HCH, double &B, double &C, int &ierr, std::string &herr)
Calculate 2nd and 3rd virial coefficients for the mixture at T.
void MolarMassGross (const std::vector< double > &x, double &Mm)
Calculate molar mass of the mixture with the compositions contained in the x() input array.
void PressureGross (const double T, const double D, const std::vector< double > &xGrs, const double HCH, double &P, double &Z, int &ierr, std::string &herr)
Calculate pressure as a function of temperature and density.
void DensityGross (const double T, const double P, const std::vector< double > &xGrs, const double HCH, double &D, int &ierr, std::string &herr)
Calculate density as a function of temperature and pressure.
void GrossHv (const std::vector< double > &x, std::vector< double > &xGrs, double &HN, double &HCH)
Calculate ideal heating values based on composition.
void GrossInputs (const double T, const double P, const std::vector< double > &x, std::vector< double > &xGrs, double &Gr, double &HN, double &HCH, int &ierr, std::string &herr)
Calculate relative density and heating values based on composition.
void SetupGross ()
Initialize all the constants and parameters in the GROSS model.
void GrossMethod1 (const double Th, const double Td, const double Pd, std::vector< double > &xGrs, const double Gr, const double Hv, double &Mm, double &HCH, double &HN, int &ierr, std::string &herr)
Initialize variables required in the GROSS equation with Method 1 of the AGA 8 Part 1 publication.
void GrossMethod2 (const double Th, const double Td, const double Pd, std::vector< double > &xGrs, const double Gr, double &Hv, double &Mm, double &HCH, double &HN, int &ierr, std::string &herr)
Initialize variables required in the GROSS equation with Method 2 of the AGA 8 Part 1 publication.
Variables
static double RGross
static const int NcGross = 21
static const int MaxFlds = 21
static const double epsilon = 1e-15
static double mN2
static double mCO2
static double dPdDsave
static double xHN [MaxFlds+1]
static double MMiGross [MaxFlds+1]
static double b0 [4][4]
static double b1 [4][4]
static double b2 [4][4]
static double bCHx [3][3]
static double cCHx [3][3]
static double c0 [4][4][4]
static double c1 [4][4][4]
static double c2 [4][4][4]
Detailed Description
Implementation of AGA 8 Part 1 GROSS equation of state (Version 2.0)
This code implements routines for the calculation of thermodynamic properties from the AGA 8 Part 1 GROSS equation of state (April 2017).
The GROSS method is used for natural gas mixtures and requires less detailed composition information than the DETAIL method. It can use either:
Method 1: volumetric gross heating value, relative density, and mole fraction of CO2
Method 2: relative density and mole fractions of nitrogen and CO2
Component order for composition array: 1 - Methane 8 - Isopentane 15 - Hydrogen 2 - Nitrogen 9 - n-Pentane 16 - Oxygen 3 - Carbon dioxide 10 - n-Hexane 17 - Carbon monoxide 4 - Ethane 11 - n-Heptane 18 - Water 5 - Propane 12 - n-Octane 19 - Hydrogen sulfide 6 - Isobutane 13 - n-Nonane 20 - Helium 7 - n-Butane 14 - n-Decane 21 - Argon
Note
SetupGross() must be called once before using any other routines
Author
Eric W. Lemmon (NIST)
Ian H. Bell (NIST)
Volker Heinemann (RMG Messtechnik GmbH)
Jason Lu (Thermo Fisher Scientific)
Copyright
Public domain (NIST)
Definition in file Gross.cpp.
Function Documentation
Bmix()
void Bmix (const double T, const std::vector< double > & xGrs, const double HCH, double & B, double & C, int & ierr, std::string & herr)
Calculate 2nd and 3rd virial coefficients for the mixture at T.
Parameters
T Temperature (K)
xGrs Compositions of the equivalent hydrocarbon, nitrogen, and CO2 (mole fractions)
HCH Molar ideal gross heating value of the equivalent hydrocarbon (kJ/mol) at 298.15 K
[out] B Second virial coefficient (dm^3/mol)
[out] C Third virial coefficient (dm^6/mol^2)
[out] ierr Error number (0 indicates no error)
[out] herr Error message if ierr is not equal to zero
Definition at line 406 of file Gross.cpp.
{
    // Sub Bmix(T, xGrs, HCH, B, C, ierr, herr)
    // Calculate 2nd and 3rd virial coefficients for the mixture at T.
    // Inputs:
    //      T - Temperature (K)
    //   xGrs - Compositions of the equivalent hydrocarbon, nitrogen, and CO2 (mole fractions)
    //    HCH - Molar ideal gross heating value of the equivalent hydrocarbon (kJ/mol) at 298.15 K
    // Outputs:
    //      B - Second virial coefficient (dm^3/mol)
    //      C - Third virial coefficient (dm^6/mol^2)
    //   ierr - Error number (0 indicates no error)
    //   herr - Error message if ierr is not equal to zero
    double bCH[3], cCH[3], BB[4][4], CC[4][4][4];
    const double onethrd = 1.0 / 3.0;
    ierr = 0;
    herr = "";
    B = 0;
    C = 0;
    // Temperature dependent Bi and Ci values for obtaining B(CH-CH) and C(CH-CH-CH)
    for (int i = 0; i <= 2; ++i){
        bCH[i] = bCHx[0][i] + bCHx[1][i]*T + bCHx[2][i]*pow(T, 2);
        cCH[i] = cCHx[0][i] + cCHx[1][i]*T + cCHx[2][i]*pow(T, 2);
    }
    // Bij and Cijk values for nitrogen and CO2
    for(int i = 2; i <= 3; ++i){
        for(int j = i; j <= 3; ++j){
            BB[i][j] = b0[i][j] + b1[i][j] * T + b2[i][j]*pow(T, 2);
            for(int k = j; k <= 3; ++k){
                CC[i][j][k] = c0[i][j][k] + c1[i][j][k] * T + c2[i][j][k]*pow(T, 2);
            }
        }
    }
    // Bij values for use in calculating Bmix
    BB[1][1] = bCH[0] + bCH[1]*HCH + bCH[2]*pow(HCH, 2); // B(CH-CH) for the equivalent hydrocarbon
    BB[1][2] = (0.72 + 0.00001875 * pow(320 - T, 2))*(BB[1][1] + BB[2][2])/2.0; // B(CH-N2)
    if (BB[1][1]*BB[3][3] < 0){
        ierr = 4; herr = "Invalid input in Bmix routine";
        return;
    }
    BB[1][3] = -0.865 * sqrt(BB[1][1] * BB[3][3]); // B(CH-CO2)
    // Cijk values for use in calculating Cmix
    CC[1][1][1] = cCH[0] + cCH[1] * HCH + cCH[2] * pow(HCH, 2); // C(CH-CH-CH) for the equivalent hydrocarbon
    if (CC[1][1][1] < 0 || CC[3][3][3] < 0){
        ierr = 5; herr = "Invalid input in Bmix routine";
        return;
    }
    CC[1][1][2] = (0.92 + 0.0013 * (T - 270)) * pow(pow(CC[1][1][1], 2) * CC[2][2][2], onethrd); // C(CH-CH-N2)
    CC[1][2][2] = (0.92 + 0.0013 * (T - 270)) * pow(pow(CC[2][2][2], 2) * CC[1][1][1], onethrd); // C(CH-N2-N2)
    CC[1][1][3] = 0.92 * pow(pow(CC[1][1][1], 2) * CC[3][3][3], onethrd); // C(CH-CH-CO2)
    CC[1][3][3] = 0.92 * pow(pow(CC[3][3][3], 2) * CC[1][1][1], onethrd); // C(CH-CO2-CO2)
    CC[1][2][3] = 1.1 * pow(CC[1][1][1] * CC[2][2][2] * CC[3][3][3], onethrd); // C(CH-N2-CO2)
    // Calculate Bmix and Cmix
    for (std::size_t i = 1; i <= 3; ++i){
        for(std::size_t j = i; j <= 3; ++j){
            if (i == j){
                B += BB[i][i]*pow(xGrs[i], 2);
            }
            else{
                B += 2*BB[i][j]*xGrs[i]*xGrs[j];
            }
            for(std::size_t k = j; k <= 3; ++k){
                if (i == j && j == k) {
                    C += CC[i][i][i]*pow(xGrs[i], 3);
                }
                else if (i != j && j != k && i != k){
                    C += 6*CC[i][j][k]*xGrs[i]*xGrs[j]*xGrs[k];
                }
                else{
                    C += 3*CC[i][j][k]*xGrs[i]*xGrs[j]*xGrs[k];
                }
            }
        }
    }
}
References b0, b1, b2, bCHx, c0, c1, c2, and cCHx.
Referenced by Bmix_wrapper(), GrossMethod1(), GrossMethod2(), and PressureGross().
DensityGross()
void DensityGross (const double T, const double P, const std::vector< double > & xGrs, const double HCH, double & D, int & ierr, std::string & herr)
Calculate density as a function of temperature and pressure.
This is an iterative routine that calls PressureGross to find the correct state point. Generally only 6 iterations at most are required. If the iteration fails to converge, the ideal gas density and an error message are returned.
Parameters
T Temperature (K)
P Pressure (kPa)
xGrs Compositions of the equivalent hydrocarbon, nitrogen, and CO2 (mole fractions)
HCH Molar ideal gross heating value of the hydrocarbon components (kJ/mol) at 298.15 K. Call subroutine GrossHv or GrossInputs first to obtain HCH.
[out] D Density (mol/l)
[out] ierr Error number (0 indicates no error)
[out] herr Error message if ierr is not equal to zero
Definition at line 233 of file Gross.cpp.
{
    // Sub DensityGross(T, P, xGrs, HCH, D, ierr, herr)
    //
    // Calculate density as a function of temperature and pressure.  This is an iterative routine that calls PressureGross
    // to find the correct state point.  Generally only 6 iterations at most are required.
    // If the iteration fails to converge, the ideal gas density and an error message are returned.
    //
    // Inputs:
    //      T - Temperature (K)
    //      P - Pressure (kPa)
    //   xGrs - Compositions of the equivalent hydrocarbon, nitrogen, and CO2 (mole fractions)
    //    HCH - Molar ideal gross heating value of the hydrocarbon components (kJ/mol) at 298.15 K
    //          *** Call subroutine GrossHv or GrossInputs first to obtain HCH. ***
    //
    // Outputs:
    //      D - Density (mol/l)
    //   ierr - Error number (0 indicates no error)
    //   herr - Error message if ierr is not equal to zero
    double plog, vlog, P2, Z, dpdlv, vdiff, tolr;
    ierr = 0;
    herr = "";
    if (P < epsilon){
        D = 0; return;
    }
    tolr = 0.0000001;
    D = P / RGross / T;       //Ideal gas estimate
    plog = log(P);
    vlog = -log(D);
    for(int it = 1; it <= 20; ++it){
        if(vlog < -7 || vlog > 100){
            ierr = 1;
            herr = "Calculation failed to converge in GROSS method, ideal gas density returned.";
            D = P/RGross/T;
            return;
        }
        D = exp(-vlog);
        PressureGross(T, D, xGrs, HCH, P2, Z, ierr, herr);
        if (ierr > 0){ return; }
        if(dPdDsave < epsilon || P2 < epsilon){
            vlog += 0.1;
        }
        else{
            // Find the next density with a first order Newton's type iterative scheme, with
            // log(P) as the known variable and log(v) as the unknown property.
            // See AGA 8 publication for further information.
            dpdlv = -D * dPdDsave;     // d(p)/d[log(v)]
            vdiff = (log(P2) - plog) * P2 / dpdlv;
            vlog = vlog - vdiff;
            if (std::abs(vdiff) < tolr){
                if (P2 < 0){
                    ierr = 10;
                    herr = "Calculation failed to converge in the GROSS method, ideal gas density returned.";
                    D = P/RGross/T;
                    return;
                }
                // Iteration converged
                D = exp(-vlog);
                return;
            }
        }
    }
    ierr = 10;
    herr = "Calculation failed to converge in the GROSS method, ideal gas density returned.";
    D = P/RGross/T;
}
References dPdDsave, epsilon, PressureGross(), and RGross.
Referenced by DensityGross_wrapper(), and GrossInputs().
GrossHv()
void GrossHv (const std::vector< double > & x, std::vector< double > & xGrs, double & HN, double & HCH)
Calculate ideal heating values based on composition.
The mole fractions in the mixture are required in this routine, not just xCH, xN2, and xCO2.
Parameters
x Molar compositions of all components in the mixture. The order in this array is given at the top of this code.
[out] xGrs Compositions of the equivalent hydrocarbon, nitrogen, and CO2 (mole fractions)
[out] HN Molar ideal gross heating value of the mixture (kJ/mol) at 298.15 K
[out] HCH Molar ideal gross heating value of the equivalent hydrocarbon (kJ/mol) at 298.15 K
Definition at line 313 of file Gross.cpp.
{
    // Sub GrossHv(x, xGrs, HN, HCH)
    //
    // Calculate ideal heating values based on composition.  The mole fractions in the mixture are required in this routine, not
    //   just xCH, xN2, and xCO2.
    //
    // Inputs:
    //     x - Molar compositions of all components in the mixture.  The order in this array is given at the top of this code.
    //
    // Outputs:
    //  xGrs - Compositions of the equivalent hydrocarbon, nitrogen, and CO2 (mole fractions)
    //    HN - Molar ideal gross heating value of the mixture (kJ/mol) at 298.15 K
    //   HCH - Molar ideal gross heating value of the equivalent hydrocarbon (kJ/mol) at 298.15 K
    xGrs.resize(4);
    xGrs[1] = 1 - x[2] - x[3];
    xGrs[2] = x[2];
    xGrs[3] = x[3];
    HN = 0;
    for(std::size_t i = 1; i <= NcGross; ++i){
        HN += x[i]*xHN[i];
    }
    HCH = 0;
    if (xGrs[1] > 0){
        HCH = HN / xGrs[1];
    }
}
References NcGross, and xHN.
Referenced by GrossHv_wrapper(), and GrossInputs().
GrossInputs()
void GrossInputs (const double T, const double P, const std::vector< double > & x, std::vector< double > & xGrs, double & Gr, double & HN, double & HCH, int & ierr, std::string & herr)
Calculate relative density and heating values based on composition.
This routine should only be used to get these two values for use as inputs to Method 1 or Method 2, and not for the relative density for any T and P. All of the mole fractions in the mixture are required in this routine, not just xCH, xN2, and xCO2.
Parameters
T Temperature (K), generally a reference temperature for relative density
P Pressure (kPa), generally a reference pressure for relative density
x Molar compositions of all components in the mixture. The order in this array is given at the top of this code.
[out] xGrs Compositions of the equivalent hydrocarbon, nitrogen, and CO2 (mole fractions)
[out] Gr Relative density at T and P
[out] HN Molar ideal gross heating value of the mixture (kJ/mol) at 298.15 K
[out] HCH Molar ideal gross heating value of the equivalent hydrocarbon (kJ/mol) at 298.15 K
[out] ierr Error number (0 indicates no error)
[out] herr Error message if ierr is not equal to zero
Definition at line 359 of file Gross.cpp.
{
    // Sub GrossInputs(T, P, x, xGrs, Gr, HN, HCH, ierr, herr)
    // Calculate relative density and heating values based on composition.  This routine should only be used to get these
    //   two values for use as inputs to Method 1 or Method 2, and not for the relative density for any T and P.
    //   All of the mole fractions in the mixture are required in this routine, not just xCH, xN2, and xCO2.
    // Inputs:
    //      T - Temperature (K), generally a reference temperature for relative density
    //      P - Pressure (kPa), generally a reference pressure for relative density
    //      x - Molar compositions of all components in the mixture.  The order in this array is given at the top of this code.
    // Outputs:
    //   xGrs - Compositions of the equivalent hydrocarbon, nitrogen, and CO2 (mole fractions)
    //     Gr - Relative density at T and P
    //     HN - Molar ideal gross heating value of the mixture (kJ/mol) at 298.15 K
    //    HCH - Molar ideal gross heating value of the equivalent hydrocarbon (kJ/mol) at 298.15 K
    //   ierr - Error number (0 indicates no error)
    //   herr - Error message if ierr is not equal to zero
    double Bref, Zref, Mref, Z, D, Mm;
    xGrs.resize(4);
    ierr = 0;
    herr = "";
    GrossHv(x, xGrs, HN, HCH);
    Bref = -0.12527 + 0.000591*T - 0.000000662*pow(T, 2);   // 2nd virial coefficient of the reference fluid at T
    Zref = 1 + Bref*P/RGross/T;                             // Z of the reference fluid at T and P
    Mref = 28.9625;
    MolarMassGross(x, Mm);
    DensityGross(T, P, xGrs, HCH, D, ierr, herr);           // Density of the input fluid at T and D
    Z = P / T / D / RGross;                                 // Z of the input fluid at T and D
    Gr = Mm * Zref / Mref / Z;
}
References DensityGross(), GrossHv(), MolarMassGross(), and RGross.
Referenced by GrossInputs_wrapper().
GrossMethod1()
void GrossMethod1 (const double Th, const double Td, const double Pd, std::vector< double > & xGrs, const double Gr, const double Hv, double & Mm, double & HCH, double & HN, int & ierr, std::string & herr)
Initialize variables required in the GROSS equation with Method 1 of the AGA 8 Part 1 publication.
Method 1 requires inputs of volumetric gross heating value, relative density, and mole fraction of CO2.
Parameters
Th Reference temperature for heating value (K)
Td Reference temperature for density (K)
Pd Reference pressure for density (kPa)
xGrs Array of size 3 with the molar composition of CO2 in the 3rd position. xCH and xN2 are returned in this array.
Gr Relative density at Td and Pd
Hv Volumetric ideal gross heating value (MJ/m^3) at Th
[out] Mm Molar mass (g/mol)
[out] HCH Molar ideal gross heating value of the equivalent hydrocarbon (kJ/mol) at 298.15 K
[out] HN Molar ideal gross heating value of the mixture (kJ/mol) at 298.15 K
[out] ierr Error number (0 indicates no error)
[out] herr Error message if ierr is not equal to zero
Definition at line 510 of file Gross.cpp.
{
    // Sub GrossMethod1(Th, Td, Pd, xGrs, Gr, Hv, Mm, HCH, HN, ierr, herr)
    // Initialize variables required in the GROSS equation with Method 1 of the AGA 8 Part 1 publication.
    // Method 1 requires inputs of volumetric gross heating value, relative density, and mole fraction of CO2.
    //
    // Inputs:
    //     Th - Reference temperature for heating value (K)
    //     Td - Reference temperature for density (K)
    //     Pd - Reference pressure for density (kPa)
    //   xGrs - Array of size 3 with the molar composition of CO2 in the 3rd position.  xCH and xN2 are returned in this array.
    //     Gr - Relative density at Td and Pd
    //     Hv - Volumetric ideal gross heating value (MJ/m^3) at Th
    //
    // Outputs:
    //   xGrs - Compositions of the equivalent hydrocarbon, nitrogen, and CO2 (mole fractions)
    //     Mm - Molar mass (g/mol)
    //    HCH - Molar ideal gross heating value of the equivalent hydrocarbon (kJ/mol) at 298.15 K
    //     HN - Molar ideal gross heating value of the mixture (kJ/mol) at 298.15 K
    //   ierr - Error number (0 indicates no error)
    //   herr - Error message if ierr is not equal to zero
    double xCH, xN2, xCO2, Zd, Zold, G1, G2, Bref, Zref, B, C;
    ierr = 0;
    herr = "";
    if (Gr < epsilon){ierr = 1; herr = "Invalid input for relative density"; return;}
    if (Hv < epsilon){ierr = 2; herr = "Invalid input for heating value"; return;}
    xCO2 = xGrs[3];
    Zd = 1;
    G1 = -2.709328;
    G2 = 0.021062199;
    Bref = -0.12527 + 0.000591*Td - 0.000000662*pow(Td, 2);              // [dm^3/mol]
    Zref = (1 + Pd / RGross / Td * Bref);
    for (int i = 0; i < 20; ++i){
        Zold = Zd;
        HN = Zd*RGross*Td/Pd*Hv*(1 + 0.0001027*(Th - 298.15));          // [kJ/mol] at 25 C
        Mm = Gr*Zd*28.9625 / Zref;                                     // [g/mol]
        xCH = (Mm + (xCO2 - 1) * mN2 - xCO2 * mCO2 - G2 * HN) / (G1 - mN2);
        xN2 = 1 - xCH - xCO2;
        if (xN2 < 0){
            ierr = 3; herr = "Negative nitrogen value in GROSS method 1 setup";
            return;
        }
        HCH = HN / xCH;
        xGrs[1] = xCH;
        xGrs[2] = xN2;
        Bmix(Td, xGrs, HCH, B, C, ierr, herr);
        if (ierr > 0){
            return;
        }
        Zd = 1 + B*Pd/RGross/Td;
        if(std::abs(Zold - Zd) < 0.0000001) { break; }
    }
}
References Bmix(), epsilon, mCO2, mN2, and RGross.
Referenced by GrossMethod1_wrapper().
GrossMethod2()
void GrossMethod2 (const double Th, const double Td, const double Pd, std::vector< double > & xGrs, const double Gr, double & Hv, double & Mm, double & HCH, double & HN, int & ierr, std::string & herr)
Initialize variables required in the GROSS equation with Method 2 of the AGA 8 Part 1 publication.
Method 2 requires inputs of relative density and mole fractions of nitrogen and CO2.
Parameters
Th Reference temperature for heating value (K)
Td Reference temperature for density (K)
Pd Reference pressure for density (kPa)
xGrs Array of size 3 with the molar composition of N2 in the 2nd position and CO2 in the 3rd position. xCH is returned in this array.
Gr Relative density at Td and Pd
[out] Hv Volumetric ideal gross heating value (MJ/m^3) at Th
[out] Mm Molar mass (g/mol)
[out] HCH Molar ideal gross heating value of the equivalent hydrocarbon (kJ/mol) at 298.15 K
[out] HN Molar ideal gross heating value of the mixture (kJ/mol) at 298.15 K
[out] ierr Error number (0 indicates no error)
[out] herr Error message if ierr is not equal to zero
Definition at line 586 of file Gross.cpp.
{
    // Sub GrossMethod2(Th, Td, Pd, xGrs, Gr, Hv, Mm, HCH, HN, ierr, herr)
    // Initialize variables required in the GROSS equation with Method 2 of the AGA 8 Part 1 publication.
    // Method 2 requires inputs of relative density and mole fractions of nitrogen and CO2.
    //
    // Inputs:
    //     Th - Reference temperature for heating value (K)
    //     Td - Reference temperature for density (K)
    //     Pd - Reference pressure for density (kPa)
    //   xGrs - Array of size 3 with the molar composition of N2 in the 2nd position and CO2 in the 3rd position.  xCH is returned in this array.
    //     Gr - Relative density at Td and Pd
    //
    // Outputs:
    //   xGrs - Compositions of the equivalent hydrocarbon, nitrogen, and CO2 (mole fractions)
    //     Hv - Volumetric ideal gross heating value (MJ/m^3) at Th
    //     Mm - Molar mass (g/mol)
    //    HCH - Molar ideal gross heating value of the equivalent hydrocarbon (kJ/mol) at 298.15 K
    //     HN - Molar ideal gross heating value of the mixture (kJ/mol) at 298.15 K
    //   ierr - Error number (0 indicates no error)
    //   herr - Error message if ierr is not equal to zero
    double xCH, Z, Zold, Bref, Zref, MrCH, G1, G2, B, C, xN2, xCO2;
    ierr = 0;
    herr = "";
    if (Gr < epsilon){ ierr = 1; herr = "Invalid input for relative density"; return; }
    xN2 = xGrs[2];
    xCO2 = xGrs[3];
    xCH = 1 - xN2 - xCO2;
    xGrs[1] = xCH;
    Z = 1;
    G1 = -2.709328;
    G2 = 0.021062199;
    Bref = -0.12527 + 0.000591*Td - 0.000000662*pow(Td, 2);
    Zref = (1 + Pd / RGross / Td * Bref);
    for (int i = 0; i < 20; ++i){
        Zold = Z;
        Mm = Gr*Z*28.9625/Zref;
        MrCH = (Mm - xN2 * mN2 - xCO2 * mCO2)/xCH;
        HCH = (MrCH - G1) / G2;
        Bmix(Td, xGrs, HCH, B, C, ierr, herr);
        if (ierr > 0){ return; }
        Z = 1 + B * Pd / RGross / Td;
        if (std::abs(Zold - Z) < 0.0000001){ break; };
    }
    HN = HCH * xCH;
    Hv = HN / Z / RGross / Td * Pd / (1 + 0.0001027 * (Th - 298.15));
}
References Bmix(), epsilon, mCO2, mN2, and RGross.
Referenced by GrossMethod2_wrapper().
MolarMassGross()
void MolarMassGross (const std::vector< double > & x, double & Mm)
Calculate molar mass of the mixture with the compositions contained in the x() input array.
Parameters
x Composition array (mole fraction) Do not send mole percents or mass fractions in the x() array, otherwise the output will be incorrect. The sum of the compositions in the x() array must be equal to one. The order of the fluids in this array is given at the top of this code.
Mm [out] Molar mass (g/mol)
Definition at line 142 of file Gross.cpp.
{
// Sub MolarMassGross(x, Mm)
// Calculate molar mass of the mixture with the compositions contained in the x() input array
// Inputs:
//    x() - Composition (mole fraction)
//          Do not send mole percents or mass fractions in the x() array, otherwise the output will be incorrect.
//          The sum of the compositions in the x() array must be equal to one.
//          The order of the fluids in this array is given at the top of this code.
// Outputs:
//     Mm - Molar mass (g/mol)
  Mm = 0;
  for(std::size_t i = 1; i <= NcGross; ++i){
    Mm += x[i] * MMiGross[i];
  }
}
References MMiGross, and NcGross.
Referenced by GrossInputs(), and MolarMassGross_wrapper().
PressureGross()
void PressureGross (const double T, const double D, const std::vector< double > & xGrs, const double HCH, double & P, double & Z, int & ierr, std::string & herr)
Calculate pressure as a function of temperature and density.
The derivative d(P)/d(D) is also calculated for use in the iterative DensityGross subroutine (and is only returned as a common variable).
Parameters
T Temperature (K)
D Density (mol/l)
xGrs Compositions of the equivalent hydrocarbon, nitrogen, and CO2 (mole fractions)
HCH Molar ideal gross heating value of the equivalent hydrocarbon (kJ/mol) at 298.15 K. Call subroutine GrossHv or GrossInputs first to obtain HCH.
[out] P Pressure (kPa)
[out] Z Compressibility factor
[out] ierr Error number (0 indicates no error)
[out] herr Error message if ierr is not equal to zero
Note
dPdDsave - d(P)/d(D) [kPa/(mol/l)] (at constant temperature) This variable is cached in the common variables for use in the iterative density solver
Definition at line 181 of file Gross.cpp.
{
    // Sub PressureGross(T, D, xGrs, HCH, P, Z, ierr, herr)
    //
    // Calculate pressure as a function of temperature and density.  The derivative d(P)/d(D) is also calculated
    // for use in the iterative DensityGross subroutine (and is only returned as a common variable).
    //
    // Inputs:
    //      T - Temperature (K)
    //      D - Density (mol/l)
    //   xGrs - Compositions of the equivalent hydrocarbon, nitrogen, and CO2 (mole fractions)
    //    HCH - Molar ideal gross heating value of the equivalent hydrocarbon (kJ/mol) at 298.15 K
    //          *** Call subroutine GrossHv or GrossInputs first to obtain HCH. ***
    //
    // Outputs:
    //      P - Pressure (kPa)
    //      Z - Compressibility factor
    //   ierr - Error number (0 indicates no error)
    //   herr - Error message if ierr is not equal to zero
    //   dPdDsave - d(P)/d(D) [kPa/(mol/l)] (at constant temperature)
    //            - This variable is cached in the common variables for use in the iterative density solver, but not returned as an argument.
    double B = 1e30, C = 1e30;
    Z = 1;
    P = D*RGross*T;
    Bmix(T, xGrs, HCH, B, C, ierr, herr);
    if (ierr > 0) { return; }
    Z = 1 + B*D + C*pow(D, 2);
    P = D*RGross*T*Z;
    dPdDsave = RGross*T*(1 + 2*B*D + 3*C*D*D);
    if (P < 0){
        ierr = -1;
        herr = "Pressure is negative in the GROSS method.";
    }
}
References Bmix(), dPdDsave, and RGross.
Referenced by DensityGross(), and PressureGross_wrapper().
SetupGross()
void SetupGross ()
Initialize all the constants and parameters in the GROSS model.
This routine must be called once before any other routine.
Definition at line 642 of file Gross.cpp.
{
  // Initialize all the constants and parameters in the GROSS model.
  RGross = 8.31451;
  // Molar masses (g/mol).  These are the same as those in the DETAIL method.
  MMiGross[1] = 16.043;    // Methane
  MMiGross[2] = 28.0135;   // Nitrogen
  MMiGross[3] = 44.01;     // Carbon dioxide
  MMiGross[4] = 30.07;     // Ethane
  MMiGross[5] = 44.097;    // Propane
  MMiGross[6] = 58.123;    // Isobutane
  MMiGross[7] = 58.123;    // n-Butane
  MMiGross[8] = 72.15;     // Isopentane
  MMiGross[9] = 72.15;     // n-Pentane
  MMiGross[10] = 86.177;   // Hexane
  MMiGross[11] = 100.204;  // Heptane
  MMiGross[12] = 114.231;  // Octane
  MMiGross[13] = 128.258;  // Nonane
  MMiGross[14] = 142.285;  // Decane
  MMiGross[15] = 2.0159;   // Hydrogen
  MMiGross[16] = 31.9988;  // Oxygen
  MMiGross[17] = 28.01;    // Carbon monoxide
  MMiGross[18] = 18.0153;  // Water
  MMiGross[19] = 34.082;   // Hydrogen sulfide
  MMiGross[20] = 4.0026;   // Helium
  MMiGross[21] = 39.948;   // Argon
  //Initialize constants
  b0[2][2] = -0.1446;           b1[2][2] = 0.00074091;         b2[2][2] = -0.00000091195;
  b0[2][3] = -0.339693;         b1[2][3] = 0.00161176;         b2[2][3] = -0.00000204429;
  b0[3][3] = -0.86834;          b1[3][3] = 0.0040376;          b2[3][3] = -0.0000051657;
  c0[2][2][2] = 0.0078498;      c1[2][2][2] = -0.000039895;    c2[2][2][2] = 0.000000061187;
  c0[2][2][3] = 0.00552066;     c1[2][2][3] = -0.0000168609;   c2[2][2][3] = 0.0000000157169;
  c0[2][3][3] = 0.00358783;     c1[2][3][3] = 0.00000806674;   c2[2][3][3] = -0.0000000325798;
  c0[3][3][3] = 0.0020513;      c1[3][3][3] = 0.000034888;     c2[3][3][3] = -0.000000083703;
  bCHx[0][0] = -0.425468;       bCHx[1][0] = 0.002865;         bCHx[2][0] = -0.00000462073;
  bCHx[0][1] = 0.000877118;     bCHx[1][1] = -0.00000556281;   bCHx[2][1] = 0.0000000088151;
  bCHx[0][2] = -0.000000824747; bCHx[1][2] = 0.00000000431436; bCHx[2][2] = -6.08319E-12;
  cCHx[0][0] = -0.302488;       cCHx[1][0] = 0.00195861;       cCHx[2][0] = -0.00000316302;
  cCHx[0][1] = 0.000646422;     cCHx[1][1] = -0.00000422876;   cCHx[2][1] = 0.00000000688157;
  cCHx[0][2] = -0.000000332805; cCHx[1][2] = 0.0000000022316;  cCHx[2][2] = -3.67713E-12;
  // //Heating values from ISO 6976 at 25 C (kJ/mol)
  // 'xHN(1) = 890.58    'Methane
  // 'xHN(2) = 0         'Nitrogen
  // 'xHN(3) = 0         'Carbon dioxide
  // 'xHN(4) = 1560.69   'Ethane
  // 'xHN(5) = 2219.17   'Propane
  // 'xHN(6) = 2868.2    'Isobutane
  // 'xHN(7) = 2877.4    'n-Butane
  // 'xHN(8) = 3528.83   'Isopentane
  // 'xHN(9) = 3535.77   'n-Pentane
  // 'xHN(10) = 4194.95  'Hexane
  // 'xHN(11) = 4853.43  'Heptane
  // 'xHN(12) = 5511.8   'Octane
  // 'xHN(13) = 6171.15  'Nonane
  // 'xHN(14) = 6829.77  'Decane
  // 'xHN(15) = 285.83   'Hydrogen
  // 'xHN(16) = 0        'Oxygen
  // 'xHN(17) = 282.98   'Carbon monoxide
  // 'xHN(18) = 44.013   'Water
  // 'xHN(19) = 562.01   'Hydrogen sulfide
  // 'xHN(20) = 0        'Helium
  // 'xHN(21) = 0        'Argon
  // Heating values from AGA-5, 2009 at 25 C (kJ/mol)
  xHN[1] = 890.63;     // Methane
  xHN[2] = 0;          // Nitrogen
  xHN[3] = 0;          // Carbon dioxide
  xHN[4] = 1560.69;    // Ethane
  xHN[5] = 2219.17;    // Propane
  xHN[6] = 2868.2;     // Isobutane
  xHN[7] = 2877.4;     // n-Butane
  xHN[8] = 3528.83;    // Isopentane
  xHN[9] = 3535.77;    // n-Pentane
  xHN[10] = 4194.95;   // Hexane
  xHN[11] = 4853.43;   // Heptane
  xHN[12] = 5511.8;    // Octane
  xHN[13] = 6171.15;   // Nonane
  xHN[14] = 6829.77;   // Decane
  xHN[15] = 285.83;    // Hydrogen
  xHN[16] = 0;         // Oxygen
  xHN[17] = 282.98;    // Carbon monoxide
  xHN[18] = 44.016;    // Water
  xHN[19] = 562.01;    // Hydrogen sulfide
  xHN[20] = 0;         // Helium
  xHN[21] = 0;         // Argon
  mN2 = MMiGross[2];
  mCO2 = MMiGross[3];
}
References b0, b1, b2, bCHx, c0, c1, c2, cCHx, mCO2, MMiGross, mN2, RGross, and xHN.
Referenced by EMSCRIPTEN_BINDINGS().
Variable Documentation
b0
double b0[4][4] static
Definition at line 130 of file Gross.cpp.
Referenced by Bmix(), and SetupGross().
b1
double b1[4][4] static
Definition at line 130 of file Gross.cpp.
Referenced by Bmix(), and SetupGross().
b2
double b2[4][4] static
Definition at line 130 of file Gross.cpp.
Referenced by Bmix(), and SetupGross().
bCHx
double bCHx[3][3] static
Definition at line 130 of file Gross.cpp.
Referenced by Bmix(), and SetupGross().
c0
double c0[4][4][4] static
Definition at line 131 of file Gross.cpp.
Referenced by Bmix(), and SetupGross().
c1
double c1[4][4][4] static
Definition at line 131 of file Gross.cpp.
Referenced by Bmix(), and SetupGross().
c2
double c2[4][4][4] static
Definition at line 131 of file Gross.cpp.
Referenced by Bmix(), and SetupGross().
cCHx
double cCHx[3][3] static
Definition at line 130 of file Gross.cpp.
Referenced by Bmix(), and SetupGross().
dPdDsave
double dPdDsave static
Definition at line 128 of file Gross.cpp.
epsilon
const double epsilon = 1e-15 static
Definition at line 127 of file Gross.cpp.
MaxFlds
const int MaxFlds = 21 static
Definition at line 126 of file Gross.cpp.
mCO2
double mCO2 static
Definition at line 128 of file Gross.cpp.
Referenced by GrossMethod1(), GrossMethod2(), and SetupGross().
MMiGross
double MMiGross[MaxFlds+1] static
Definition at line 129 of file Gross.cpp.
Referenced by MolarMassGross(), and SetupGross().
mN2
double mN2 static
Definition at line 128 of file Gross.cpp.
Referenced by GrossMethod1(), GrossMethod2(), and SetupGross().
NcGross
const int NcGross = 21 static
Definition at line 126 of file Gross.cpp.
Referenced by GrossHv(), and MolarMassGross().
RGross
double RGross static
Definition at line 125 of file Gross.cpp.
Referenced by DensityGross(), GrossInputs(), GrossMethod1(), GrossMethod2(), PressureGross(), and SetupGross().
xHN
double xHN[MaxFlds+1] static
Definition at line 129 of file Gross.cpp.
Referenced by GrossHv(), and SetupGross().